customer/urls.py
from django.urls import path,re_path
from dal import autocomplete
from . import views

app_name = 'customer'

urlpatterns = [
    re_path(r'login/$', views.signin, name='signin'),
    re_path(r'index/$', views.index, name='index'),
    re_path(r'sign-up/$', views.sign_up, name='sign_up'),
]

user_login/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import  include, path, re_path
from django.conf import settings

urlpatterns = [
    path('',include(('customer.urls'),namespace='customer')),
    
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    
    path('api/user-details/', include(('api.user_details.urls','user_details'), namespace='api_user_details')),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <div class="l-block toggled" id="l-login">
        <div class="lb-header palette-Teal bg">
            <i class="zmdi zmdi-lock"></i>
            Login Success
        </div>
    
        <div class="lb-body">
            <p class="message center">You are successfully logged in. <br /> <a class="color_link center" href="{% url 'customer:sign_up' %}">Logout</a>
        </div>
    </div>
</body>
</html>

            